### ISSUE TITLE
Turning react web app to mobile app 1

### ISSUE THREAD

**Issue by youngmin1205** [COMP313-software-project2/COMP313-001Team1-EduCloud-#23]

**Comment by karlaluuu** [comment]
Code currently works on emulator with PWA 6/9 optimized. Image below for reference. 
![softdev2](https://user-images.githubusercontent.com/44037548/98072433-053dc900-1e34-11eb-93b6-5fcdc586cf35.png)

Commenting for suggestions or opinions.
